language: node_js
node_js:
    - "5.5"
addons:
    sauce_connect: true
sudo: false
env:
  global:
      - secure: AmG4KmgELDGWeYjQ2BNGRG/yuhwDdVPdLekr/paySTL320CxcFY7aPJPht9iSytmq95N5fbF/6I7aqEZg5SoVuaPi81a8xvj/SCeV0dE0nzHV/EwadgdkOSxZ8+ctbN1hVOrcBLsPMOrVPaWP9zBCRAC5Q1TOE/r+N0BrQMhahA=
      - secure: PEgAZikBNY1sI6j8NZ+wFQOJQa5xNY1XOryGNgfytN9rbY7WvYYiS4aXMSKfjUjtDjRcFIzskYfOLaYPPlaa928Kzo9zdZx8A55Aa/UcKdx4pze9IuaCtzUMtwuuZM8FTUiO+tmOUQJ46PN1X36Yh4CFF7BlZFynGerUwkoo3h4=
install:
    - npm -g install mocha grunt-cli serve
    - npm install
    - grunt enyo:init
before_script:
    - serve -L .. &
script:
    - echo -e "\x1b\x5b35;1m*** Starting tests...\x1b\x5b0m"
    - grunt test:sauce:chrome
    - echo -e "\x1b\x5b35;1m*** Tests complete\x1b\x5b0m"
